### ISSUE TITLE
Creating other branches

### ISSUE THREAD

**Issue by sararin** [Pringleman83/SportsBook#7]
I think this would help you update code.
Master branch could stay untouched until you build up enough features, while feature branch would allow you and other people to contribute.
Cheers, sara

**Comment by Pringleman83** [comment]
Hi Sara
I'm not very familiar / confident with github. I'll do that going forward and learn as I go, thanks!

**Comment by surister** [comment]
It'd be awesome if you could make a new branch so we can merge into it, check it and once it works 100% we merge that branch with the master branch, so it's assured that the master branch always works, for instance, with my first pull request, main branch would not work because of 2 imports (supposed to be fixed with my last pr)

**Comment by Pringleman83** [comment]
I really appreciate all of your effort and your patience with me. I really don't get github and I'm trying to catch up. I was under the impression that anybody could create a branch. I've created a development branch now.

I've imported your changes and to the master and I'll try it out a little later. Thanks again for what you've done.

I misunderstood what Sara said earlier about not having to change other files. I thought she meant that the function names would update automatically. I see you've fixed all that anyway.

If you think I need to do something, please feel free to let me know. I'll pick it up eventually!
